http_server:
  addresses: ""
  port: 8080
  read_timeout: 60s
  write_timeout: 60s
  read_header_timeout: 60s
  shutdown_timeout: 60s
database:
  type: mongodb
  mongo:
    address: "tphuc:tphuc@cluster0.f6wcv.mongodb.net/social?retryWrites=true&w=majority"
    timeout: 15s
    username: "tphuc"
    password: "tphuc"
    database: "social"
cloudinary:
  url: "cloudinary://844292466881975:futoF6yjg7beCGAPBxawGwVVQ58@dgyqcl1ef"
jwt:
  duration: 24h
  
mail:
  email: "activitiessocial66@gmail.com"
  password: "conga99#"
  smtp:
    host_mail: "smtp.gmail.com"
    port_mail: "587"
  confirm_timeout: 120s
  src_template: "internal/pkg/mail/template/index.html"