http_server:
  addresses: ""
  port: 8080
  read_timeout: 60s
  write_timeout: 60s
  read_header_timeout: 60s
  shutdown_timeout: 60s
database:
  type: mongodb
  mongo:
    address: ""
    timeout: 15s
    username: "tphuc"
    password: "tphuc"
    database: "social"
cloudinary:
  url: ""
jwt:
  duration: 24h