export enum LoginTypes {
  FETCH_LOGIN_REQUEST = 'FETCH_LOGIN_REQUEST',
  FETCH_LOGIN_SUCCESS = 'FETCH_LOGIN_SUCCESS',
  FETCH_LOGIN_FAILURE = 'FETCH_LOGIN_FAILURE',
}
export enum RegisterTypes {
  FETCH_REGISTER_REQUEST = 'FETCH_REGISTER_REQUEST',
  FETCH_REGISTER_SUCCESS = 'FETCH_REGISTER_SUCCESS',
  FETCH_REGISTER_FAILURE = 'FETCH_REGISTER_FAILURE',
}
export enum LoadAuth {
  LOAD_AUTH_REQUEST = 'LOAD_AUTH_REQUEST',
  LOAD_AUTH_SUCCESS = 'LOAD_AUTH_SUCCESS',
  LOAD_AUTH_FAILURE = 'LOAD_AUTH_FAILURE',
}
